name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    pull_request:
      - main
jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/demo-github-actions:${{ github.sha }} .
          docker tag ${{ env.DOCKER_USERNAME }}/demo-github-actions:${{ github.sha }} ${{ env.DOCKER_USERNAME }}/demo-github-actions:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/demo-github-actions:${{ github.sha }}
          docker push ${{ env.DOCKER_USERNAME }}/demo-github-actions:latest
